services:
  index-tts:
    #build:
    #  context: .
    #  args:
    #    http_proxy: ${http_proxy}
    #    https_proxy: ${https_proxy}
    image: anyshpm/index-tts:2.0-beta
    container_name: index-tts
    #restart: unless-stopped
    ports:
      - "7860:7860"
    volumes:
      # Mount checkpoints to avoid redownloading on container recreation
      - ./checkpoints:/app/index-tts/checkpoints
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: [ gpu ]
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
      - http_proxy=http://pi4.utopia.anyshpm.com:8081
      - https_proxy=http://pi4.utopia.anyshpm.com:8081
